export const mountainScene = Object.freeze({
  id: "mountain",
  entryMode: "external",
  name: "爬山岛",
  label: "第 一 站 · 爬 山 场 景",
  accent: "#9b745c",
  description: "第一站：沿着山路走向云端。",
  sceneDescription: "走过绳桥就能开始爬山。完成这段旅程后，工作岛将会解锁。",
  legendState: "下一站",
  completedLegendState: "已完成",
  completedAtOrder: 2,
  unlocksOrder: 2,
  completionLabel: "完成爬山，解锁工作岛",
  completionMessage: "爬山已完成，通往工作岛的桥已解锁。",
  replayCompletionMessage: "爬山剧情已重温完成。",
  closeMessage: "已返回世界地图，爬山进度会在下次进入时恢复。",
  openFailureMessage: "爬山剧情暂时无法恢复，请稍后重试。",
});
