export const mountainScene = Object.freeze({
  id: "mountain",
  entryMode: "confirmed-external",
  entryLabel: "进入爬山剧情",
  name: "爬山岛",
  label: "第 一 站 · 爬 山 场 景",
  accent: "#9b745c",
  description: "第一站：沿着山路走向云端。",
  sceneDescription: "走过绳桥后将从咖啡馆邀约开始这段爬山旅程。完整结束后，工作岛才会解锁。",
  legendState: "已解锁",
  completedLegendState: "已完成",
  completedAtOrder: 2,
  unlocksOrder: 2,
  completionMessage: "爬山已完成，通往工作岛的桥已解锁。",
  replayCompletionMessage: "爬山剧情已重温完成。",
  closeMessage: "已返回世界地图，爬山进度会在下次进入时恢复。",
  openFailureMessage: "爬山剧情暂时无法恢复，请稍后重试。",
});
