const choice = (id, text, analysis, dimensions, feedback, companionMood = "") => ({
  id,
  text,
  analysis,
  dimensions,
  feedback,
  companionMood,
});

export const MOUNTAIN_STAGES = [
  {
    id: "invitation",
    kind: "choice",
    scene: "cafe",
    title: "周末邀约",
    narration: "{companion}把星空谷的路线推到你面前，期待地等着回答。",
    prompt: "这个周末，要不要一起去爬山？",
    dimensions: ["规划意识", "风险偏好", "关系边界", "人生愿景"],
    choices: [
      choice("planned", "好呀，不过我先列个装备清单，查天气和备用路线吧。", "极度务实，偏好可控的冒险，需要清晰规划并拒绝无准备的失控。", ["规划意识", "风险偏好"], "{companion}笑着把路线发给你，开始和你核对装备。", "安心"),
      choice("escape", "一言为定，周五下班就开飞行模式，一起去山里做快乐的失踪人口！", "追求生命体验的纯粹度，厌恶被功绩主义异化，渴望灵魂共振。", ["人生愿景", "体验偏好"], "{companion}眼睛一亮，和你约好暂时逃离城市。", "兴奋"),
      choice("devoted", "只要你想去，再险我也陪你。", "将陪伴与牺牲视为爱的语言，容易让渡自我边界。", ["关系边界", "风险偏好"], "{companion}收起手机，郑重地点了点头。", "感动"),
    ],
    recordsEvidence: true,
    nextStageId: "fatigue",
    waypoint: "cafe-table",
  },
  {
    id: "fatigue",
    kind: "choice",
    scene: "mountain",
    title: "疲惫与抱怨",
    narration: "陡峭崖壁让你们体力透支，手机也失去了信号。",
    prompt: "{companion}苦笑着说这像在玩命，你会怎么回应？",
    dimensions: ["问题解决", "情绪共情", "压力归责"],
    choices: [
      choice("solve", "拿出地图或指南针：别慌，我们先核对海拔和剩余路程。", "目标导向，习惯通过解决客观问题获得安全感。", ["问题解决", "压力应对"], "{companion}接过地图，呼吸慢慢平稳下来。", "放松"),
      choice("empathize", "递过水壶：是挺坑的，累了就多休整一会儿，大不了原路返回。", "人的感受高于事情功绩，爱的语言是理解与接纳。", ["情绪共情", "关系支持"], "{companion}喝了口水，靠着岩石松了口气。", "被理解"),
      choice("blame", "是你非要找这种野线，现在只能硬着头皮上了。", "压力下倾向推卸责任，害怕承担失败后果。", ["压力归责", "防御机制"], "{companion}沉默下来，把视线移向湿滑的山路。", "退缩"),
    ],
    recordsEvidence: true,
    nextStageId: "slip",
    waypoint: "lower-cliff",
  },
  {
    id: "slip",
    kind: "choice",
    scene: "mountain",
    title: "山腰滑落",
    narration: "暴雨骤降，{companion}脚下碎石松动，身体向下滑去。",
    prompt: "生死一瞬，你的第一反应是？",
    dimensions: ["掌控倾向", "行动方式", "高压反应"],
    choices: [
      choice("command", "大吼：别往下看！看着我！把另一只手给我！", "危机中强烈寻求主导位置，带有掌控与救世主倾向。", ["掌控倾向", "高压反应"], "你的声音穿过雨幕，{companion}努力把手伸向你。", "紧张"),
      choice("support", "一声不吭趴进泥里，用身体和腿卡住岩石，给{companion}一个支点。", "以服务行动表达关心，不善言辞但可靠。", ["行动方式", "高压反应"], "{companion}踩稳支点，终于从泥坡上撑起身。", "安心"),
      choice("freeze", "呼吸骤停，大脑空白半秒后才慌乱扑向崖边。", "高刺激环境中容易信息超载，需要更多时间处理。", ["高压反应", "心理边界"], "{companion}抓紧树根，雨声里只剩急促的呼吸。", "恐慌"),
    ],
    recordsEvidence: true,
    nextStageId: "storm-thought",
    waypoint: "mid-cliff",
  },
  {
    id: "storm-thought",
    kind: "choice",
    scene: "mountain",
    title: "暴雨念头",
    narration: "雷声、雨声和泥地摩擦声包围着你们，{companion}冻得发抖。",
    prompt: "在失控的暴雨里，最先闪过你脑海的念头是？",
    dimensions: ["目标执着", "沉没成本", "刺激追求", "保护欲"],
    choices: [
      choice("finish", "既然设定了登顶的目标，就算被暴雨吞噬也必须按计划完成，绝不允许失控。", "在失控环境中仍执着维持既定目标与秩序，风险阈值较高。", ["目标执着", "掌控倾向"], "你咬紧牙关，把目光投向更高处的石壁。", "紧绷"),
      choice("extreme", "越是生死一线的绝境，强行登顶后的风景和我们的羁绊才越是刻骨铭心。", "追求极端体验与高浓度关系共振，容易把风险转化为意义感。", ["刺激追求", "关系融合"], "闪电照亮山脊，你感到一瞬近乎疯狂的清醒。", "忐忑"),
      choice("retreat", "失温的风险已经超过临界值，别管什么沉没成本，现在立刻下撤才是唯一的生路。", "能够识别风险临界点并果断放弃沉没成本，重视现实安全边界。", ["风险决策", "边界意识"], "你开始寻找安全下撤的方向。", "安心"),
      choice("protect", "什么登顶的执念都不重要了，我现在唯一的任务就是带她活着回到安全区。", "危机中把伴侣安全置于目标之上，以保护和承担表达关系责任。", ["保护欲", "关系责任"], "你靠近她，用身体挡住一阵横扫的冷风。", "安心"),
    ],
    recordsEvidence: true,
    nextStageId: "cave-repair",
    waypoint: "storm-cliff",
  },
  {
    id: "cave-repair",
    kind: "choice",
    scene: "mountain",
    title: "岩洞修复",
    narration: "岩壁挡住了狂风，{companion}靠着石壁，仍在轻轻发抖。",
    prompt: "面对濒临崩溃的{companion}，你会怎么做？",
    dimensions: ["冲突修复", "爱的表达", "情绪边界"],
    choices: [
      choice("lecture", "边擦雨水边说：你看，我早说该做备用计划吧？", "事后强调自身正确性，情绪觉察较弱。", ["冲突修复", "情绪觉察"], "{companion}把保温杯抱得更紧，没有马上回答。", "委屈"),
      choice("hug", "把{companion}紧紧抱在怀里，不断说：没事了，有我在。", "通过身体接触与言语肯定确认彼此安全。", ["爱的表达", "情绪支持"], "{companion}在你的怀里慢慢止住了颤抖。", "安心"),
      choice("space", "倒一杯热咖啡递给{companion}，然后退开半步，让{companion}安静缓冲。", "尊重伴侣的能量边界，擅长无声而坚定的冲突修复。", ["冲突修复", "情绪边界"], "岩洞里安静下来，雨声也变得遥远。", "放松"),
    ],
    recordsEvidence: true,
    nextStageId: "home-message",
    waypoint: "cave",
  },
  {
    id: "home-message",
    kind: "choice",
    scene: "apartment",
    title: "回家消息",
    narration: "回到公寓后，泥泞的装备留在玄关，聊天窗口的光还亮着。",
    prompt: "面对这段突然加深的关系，你会发出怎样的消息？",
    dimensions: ["依恋倾向", "亲密承受力", "脆弱接纳"],
    choices: [
      choice("avoid", "先不主动发消息，明天白天再客套地问一句：昨晚休息得好吗？", "高强度亲密后倾向拉开距离，以恢复控制感。", ["依恋倾向", "关系边界"], "光标闪烁了一会儿，你把手机放回桌面。", "失落"),
      choice("secure", "我的腿还在发软，客厅也被我踩脏了。但雨里的你比咖啡馆里的完美标签迷人一万倍。", "能接纳关系中的毛边与脆弱，把共同危机视为深度连接。", ["依恋倾向", "脆弱接纳"], "消息发送出去，屏幕很快亮起温柔的回复。", "感动"),
      choice("anxious", "发一大段复盘，反复确认：如果你出了事我怎么办？我们以后别分开了好吗？", "危机放大被抛弃焦虑，试图以高密度情绪输出换取承诺。", ["依恋倾向", "亲密承受力"], "你反复删改长消息，城市的灯光映在屏幕上。", "压力"),
    ],
    recordsEvidence: true,
    nextStageId: "city-realization",
    waypoint: "apartment-window",
  },
  {
    id: "city-realization",
    kind: "choice",
    scene: "apartment",
    title: "城市顿悟",
    narration: "洗完澡后，你看着镜子里疲惫却鲜活的自己，窗外车河依旧井然有序。",
    prompt: "这次经历后，最强烈的念头是什么？",
    dimensions: ["安稳建设", "当下享受", "自由探索"],
    choices: [
      choice("build", "我只想在城市里深深扎根，建立一个能挡风遮雨的家。", "重视安全、秩序与长期建设。", ["安稳建设", "安全感"], "你看着玄关的泥水，第一次觉得坚固的日常如此珍贵。", "安心"),
      choice("enjoy", "未来规划算什么，我只想痛痛快快享受每一口热饭和每一次拥抱。", "经历危机后更珍视当下体验与真实感受。", ["当下享受", "生命体验"], "热水的余温还在，你决定把今晚留给真实的感受。", "温暖"),
      choice("roam", "如果安稳就是这条车河，我宁愿一直在路上，去更远更野的地方。", "向往自由、未知与没有剧本的人生。", ["自由探索", "开放性"], "你望向城市尽头，想起暴雨中异常鲜活的山脊。", "向往"),
    ],
    recordsEvidence: true,
    nextStageId: "complete",
    waypoint: "apartment-mirror",
  },
  {
    id: "complete",
    kind: "complete",
    scene: "apartment",
    title: "旅程余韵",
    narration: "这段旅程结束了，但你们的关系和对自己的理解仍会继续生长。",
    prompt: "",
    choices: [],
    recordsEvidence: false,
    nextStageId: null,
    waypoint: "apartment-door",
  },
];
